test_server_homepage:
    path:     /
    defaults: { _controller: testServerBundle:Default:index }

test_server_newserver:
    path:     /newserver
    defaults: { _controller: testServerBundle:Server:new }

test_server_newsoftware:
    path:     /newsoftware
    defaults: { _controller: testServerBundle:Software:new }

test_server_newversion:
    path:     /newversion/{id}
    defaults: { _controller: testServerBundle:Version:new }

test_server_editserver:
    path:     /editserver/{id}
    defaults: { _controller: testServerBundle:Server:edit }

test_server_editsoftware:
    path:     /editsoftware/{id}
    defaults: { _controller: testServerBundle:Software:edit }
test_server_editversion:
    path:     /editversion/{id}
    defaults: { _controller: testServerBundle:Version:edit }

server_listofversions:
    path:     /serverlist/{id}
    defaults: { _controller: testServerBundle:Server:listversions }

software_listofversions:
    path:     /softwarelist/{id}
    defaults: { _controller: testServerBundle:Software:listversions }
software_delete:
    path:     /softwaredelete/{id}
    defaults: { _controller: testServerBundle:Software:delete }

server_delete:
    path:     /serverdelete/{id}
    defaults: { _controller: testServerBundle:Server:delete }

version_delete:
    path:     /versiondelete/{id}/{server}
    defaults: { _controller: testServerBundle:Server:deleteVersion }
versionstoadd:
    path:     /versiontoadd/{id}
    defaults: { _controller: testServerBundle:Version:index2 }

version_ajout:
    path:     /versionajout/{id}/{idserveur}
    defaults: { _controller: testServerBundle:Version:addToServer }




